### ISSUE TITLE
DeploymentIds was renamed to TargetClusters in recent Yams versions

### ISSUE THREAD

**Issue by Maarten88** [ReubenBond/YamsDeploy#3]
I upgraded Yams and deployed a new cluster, and found that deployments were not working at all. Turned out I had to rename DeploymentIds to TargetClusters in the DeploymentConfig.json, and everything started working again.

I'm using YamsDeploy to deploy new versions so I think this change should be done here too so it'll keep being useful.

**Comment by ReubenBond** [comment]
Thanks, @Maarten88 :) Do you think you would be able to submit a PR?
